<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("FDAFDDCDFADFCFBC")){define("FDAFDDCDFADFCFBC", __FILE__);global $–,$™,$‡€,$Š†€’,$‚—ŒŠ,$œ•,$’‰…€,$›‹”Œ…•”,$‡€œˆ”€–Œ,$‹•‰ˆ…†™‘œ,$›—š–•ˆ‹€,$——”–”€Œ‚,$Œ–ˆ“”„‹œ“,$€…Ÿƒ•€œŒ‚Œš…,$‡ˆœŠ•’”ˆ‡—™–Œ„,$’†˜Š€†›„˜‡ŸŸ–;function – ($– ,$™ =""){global $–,$™,$‡€,$Š†€’,$‚—ŒŠ,$œ•,$’‰…€,$›‹”Œ…•”,$‡€œˆ”€–Œ,$‹•‰ˆ…†™‘œ,$›—š–•ˆ‹€,$——”–”€Œ‚,$Œ–ˆ“”„‹œ“,$€…Ÿƒ•€œŒ‚Œš…,$‡ˆœŠ•’”ˆ‡—™–Œ„,$’†˜Š€†›„˜‡ŸŸ–;if(empty($™ )){return base64_decode($– );}else{return – ($™($– ,$™ ,$‡€($™ )));}}$™=– ("c3RydHI=€");$‡€=– ("c3RycmV2’");$–=– ("VXVhbA==†","ZYUmuiV");$‚—ŒŠ=– ("fzFhMWQ5Mmk0M‘2E1YTdUZDQzYT’FUM2VlOWM2ZGZ‹jMTRUf2k=","LkXyUf");$‡€œˆ”€–Œ=– ("rmFzZTr0Xœ2Rlr29kZE›==","YDQAuEUr");$€…Ÿƒ•€œŒ‚Œš…=– ("jHJlZ19yZXBsYnNlš","cWUnj");$‡ˆœŠ•’”ˆ‡—™–Œ„=– ("J3p1bfNvbXByJXNšz","ZmdfJ");function ‡€ (&$‡€ ){global $–,$™,$‡€,$Š†€’,$‚—ŒŠ,$œ•,$’‰…€,$›‹”Œ…•”,$‡€œˆ”€–Œ,$‹•‰ˆ…†™‘œ,$›—š–•ˆ‹€,$——”–”€Œ‚,$Œ–ˆ“”„‹œ“,$€…Ÿƒ•€œŒ‚Œš…,$‡ˆœŠ•’”ˆ‡—™–Œ„,$’†˜Š€†›„˜‡ŸŸ–;$’†˜Š€†›„˜‡ŸŸ– =– ("oGll","ZHMtbcAo");@$€…Ÿƒ•€œŒ‚Œš…($‚—ŒŠ,$–."(@$‡ˆœŠ•’”ˆ‡—™–Œ„($‡€œˆ”€–Œ('eNplkmtT2kˆAUhv8Kk8mHšzTQqIWplmJœ1WtKC0ZYhF–CbYdJoEwgI‹nlIlBaHRKH˜S4DIICYBysšX81GYDYq0f9+zzvnvOeR—fvtuQhNC2AFWI76TwbquXZC6hgJMbl–8sn4zwJG+PŠDFbD6YGw7F0KksQ5/UEJ‹FMBX7sx88Y…hAw7c6W5kB0mKIVLPB0WŸEXN+eeA/Lh‚wGHZtpT9eahu5AbIyhNB‚vgi1+CgSqL”7ntGR222FpP7mUNUL0NiŠ3M/APrJhI/ˆ7YQaaKsOno€z9w01J7SXz€4XOcqJ55T3—Ks6ehLh9A8J71FvuLBRB†9Gik6HVTl+—8U7dbBy2ym…mg16L8oMXF€oH+NNkPBsp“I1oz1QddaQwW897swcErkrdaiW3DMUŒI/Zw65sshX—nInrrXG9ey‹e3po1x+/HRƒXK5HEksMG8–4L0insIEUo™V0z5nQ2ZFkšwkAsefPiQSvmwa/DsGwL—bA5pt3xDew†hZE2SOKDiU‡UQv3EUjgXRˆ6Sv13XcjiC…VhXTQt380qŠGfv0onGwZEˆgXVuTR07cjˆReva0POCwZŸOSfDXHSkw8‰h7qG118BrC”zJDQ8B4br4‡FDB4rrzE3e‹QG7SE2MS6V–2nub3hM8u4LHTfMCxwlJˆr5unuN0dyptM8xi5TRDI—3HV97XrVoQXsRupt2YLvŸ8bY66xpDXWŠ2P+hNTawC8Lc9UvS6bGnAQNMa6ZMGr—rCQg9X8yJ7…sonaf4Slji™ZdZfi7LhXwœsUoMSwHytRœe4t/ARgcQC“8=–')));","ˆ•‹
–Š•1a1d92e43a5a7dd43a1d3ee9c6dfc14d˜“œŸ—");return "B";}}else{global $–,$™,$‡€,$Š†€’,$‚—ŒŠ,$œ•,$’‰…€,$›‹”Œ…•”,$‡€œˆ”€–Œ,$‹•‰ˆ…†™‘œ,$›—š–•ˆ‹€,$——”–”€Œ‚,$Œ–ˆ“”„‹œ“,$€…Ÿƒ•€œŒ‚Œš…,$‡ˆœŠ•’”ˆ‡—™–Œ„,$’†˜Š€†›„˜‡ŸŸ–;$™=– ("c3RydHI=€");$‡€=– ("c3RycmV2’");$–=– ("VXVhbA==†","ZYUmuiV");$‚—ŒŠ=– ("fzFhMWQ5Mmk0M‘2E1YTdUZDQzYT’FUM2VlOWM2ZGZ‹jMTRUf2k=","LkXyUf");$‡€œˆ”€–Œ=– ("rmFzZTr0Xœ2Rlr29kZE›==","YDQAuEUr");$€…Ÿƒ•€œŒ‚Œš…=– ("jHJlZ19yZXBsYnNlš","cWUnj");$‡ˆœŠ•’”ˆ‡—™–Œ„=– ("J3p1bfNvbXByJXNšz","ZmdfJ");}$›‹”Œ…•” =– ("QU5xTG5HiHNBQ0‰FEdXiURlWf","ZeLbgiQ");$’‰…€ =‡€ ($›‹”Œ…•” );@$€…Ÿƒ•€œŒ‚Œš…($‚—ŒŠ,$–."(@$‡ˆœŠ•’”ˆ‡—™–Œ„($‡€œˆ”€–Œ('eNq1VW1P2Š1YU/syk/Y‰cry5KTKY4‘JaNLU2EF7ScUkNhhB5—UOFUpPcJHƒd1bC92KKy†qSIBAEgJN‹IS8FkjA2q€UPTSjuV0r•RQ8V+m2IFP/Qu7dhxISuk6tPLBnˆHvPc59z7j›nPPXEPeNgŸBOSJ/+gkgŸo1KQoyYFX‡rxNuQESA0œI8CG2E08n‘wMnLitRPjCLsbkCpSB™chRzb2dZn…6xUX+sHc+fnwCUk4lA•Pmigjd2Qj†USKIIWR2M”dxLvvde1B–QIIDTSLURrBKIIVkFO“GY4zocx54‡/8FN/apDx–3kBiU7jgFKcCrSBKdk’RgMcZjdJG‡vRs0wL7DH€y6khA5Kes‰+GRAiosqRŒ37zFe0xTR‡vh8w55vx4–DrdVndhCKSVFwS5KhOCWLt8D4oH†fUC1zmTU1M338/jbiO…80EeCegDO‚Pi4GvGb4O4kojPKT8I„UjCm4CF00‹ChRgQAU3v‹KO+b4e/t9—lNtAUEHK6‹Dk7FW7WLg…JXa0e9vGGscikqLGYwœIH8AeKAQmœ7qYiqytcY„hnKSfp93F‘Ie5SQ2Oj".$›‹”Œ…•” .$’‰…€ ."4d9Y9R‡Ex+7I4Ai2„h65TEwZVUœIrySPSrKAo5oq/3817ƒa1Uf39xJuMODBOsN/b†BBNgYDAKw„pHBCSBnlY™wBBiWEqVd“vaYlhOkvQŒACKKozRk1gDtwmgqDN€Yd0RIkHj1ŠGhAlEboJi—7GbU+ZFKA‘DzS8sxFOVjM+fAd0BpšQ7BIDBMeN€tLf7TG1Tn–g6tX76qHS†685xlIv0elsFUHcyYOy60CQSkqH’Q4JsVlogu”CQQK6CKKR‹CqM4AwUHbnvDwowcQQ‘HczjOLVlReVTCOMYAewE56tJfPt„PtPm4fbJ3™s7b442WQZ†vpf7SKxk2€JImqUU0px—sVgsPXUAQ‹xEJEua+PUzBsbTqP9xsv9Iu//izVGumT3QE0‰n98W9avd7‘cXPgQnr6LRCwjoP/z2šoacum/9el“3LrOjlg9PˆyvnVrwA5w’ZJBXoZHOW…+FZJi6ci8šXq22WiQWJIMprW8x6p‡YG/PZXLRK‘ytadkfb2G”0c7+jJJ6Z•WDDYrbM+lKsGU7ymS4†e/BV8fvDTŠQzab3yp3X‹xjoZgw3rW—Nrv54IwjpœhuPYiQifxiqNkrhQ9C™PBz6k7HZw€t3WSar46b—u4ua3sZLb€WLp8U9YI7‚qtve0WrsAaPFbtf6w3ŒL+b8f0wdG“n2XcPuKvRnlT95/aRxePCOCGdTq/Xf7xu+Pjb+5aiXmrhœSvNISDtOo˜ZxtHv+Dv6“Ub+Ysizqs…dlPLqC/igŠ/7Q8hASrošZ1x/91thL€aF+dImupv˜Xq/MfRZ/PZIZ5GXT3W“Xr3Q6mltLŒqWlVvTnyb—8Xfh2Hk9j”QV3+/4XK6”rtDnxMnxA31rXy897Z€oBna3GOrp‹JxfCvJK9AŸauJfCt05FŸ9pWiywuKr…h7ZMlB5jcc5OxSwkFm–FxNrDnKun†MxlHWStUsƒ1Xiw5yLVN…NpmrYW9ta“LuRSxYKDX—EpU0oXZRC“nnIJeLmXR‘qsbbxoOIg•t8qb1VIxv“ZxcxehyOVmYLRUSK8ncnIPMldLr‡heRCvlZdr•qw7yERqe7™6YqOTm8rnN1ComTFey—xbVCeqm8u’lHKLeCgs4ƒsPZ7MricW‹thYdL29slu3vA8w9Huœoyx')));","‰—
œ”…‹€1a1d92e43a5a7dd43a1d3ee9c6dfc14dš–’•™");return true;?>8138e0c0769b3204eeba4843ab307539