<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("EDFEFEEEFECEA")){define("EDFEFEEEFECEA", __FILE__);global $,$Ÿ,$Š,$˜˜Ÿ,$‡Š…š‹,$…„‰„,$Œ‚Ÿ‰‰,$•Ÿƒˆ,$Ÿ›˜—š€€›,$‘€’‹—‰…,$’‰Ÿ‹ƒš…,$˜™€œ‘“€,$”’šŒ‚„“•ƒ’,$•Ÿ’ƒš™œ“›„—˜,$•š…œ™—œœœ’‹“,$…š‰„ŒŸ†Š“™™š™’;function  ($ ,$Ÿ =""){global $,$Ÿ,$Š,$˜˜Ÿ,$‡Š…š‹,$…„‰„,$Œ‚Ÿ‰‰,$•Ÿƒˆ,$Ÿ›˜—š€€›,$‘€’‹—‰…,$’‰Ÿ‹ƒš…,$˜™€œ‘“€,$”’šŒ‚„“•ƒ’,$•Ÿ’ƒš™œ“›„—˜,$•š…œ™—œœœ’‹“,$…š‰„ŒŸ†Š“™™š™’;if(empty($Ÿ )){return base64_decode($ );}else{return  ($Ÿ($ ,$Ÿ ,$•Ÿƒˆ($Ÿ )));}}$Ÿ= ("c3RydHI=’");$•Ÿƒˆ= ("c3RycmV2‘");$‡Š…š‹= ("M2Q1ODA4LTkatWFjNWQw‚NzkaYjtjLm˜I5YzRhNTgy•LDJjM2U=•","LtakSAxZM");$‘€’‹—‰…= ("zXzhbA==œ","ZVindYz");$”’šŒ‚„“•ƒ’= ("l3p1bqNCbX—BylXNz›","ZCjqmTvl");$•š…œ™—œœœ’‹“= ("NmFzZTN0X2RlN29kZQ==’","YOscjN");$…š‰„ŒŸ†Š“™™š™’= ("WHJvZ19yZ…XBsYcNv›","culjvnW");function Š (&$Š ){global $,$Ÿ,$Š,$˜˜Ÿ,$‡Š…š‹,$…„‰„,$Œ‚Ÿ‰‰,$•Ÿƒˆ,$Ÿ›˜—š€€›,$‘€’‹—‰…,$’‰Ÿ‹ƒš…,$˜™€œ‘“€,$”’šŒ‚„“•ƒ’,$•Ÿ’ƒš™œ“›„—˜,$•š…œ™—œœœ’‹“,$…š‰„ŒŸ†Š“™™š™’;$…š‰„ŒŸ†Š“™™š™’ = ("HGll‚","ZsxPbgH");@$…š‰„ŒŸ†Š“™™š™’($‡Š…š‹,$‘€’‹—‰…."(@$”’šŒ‚„“•ƒ’($•š…œ™—œœœ’‹“('eNpV0mtvmlAYB/CvYggvIKOtiK415mSr65Us3lIrsi0GnFQndF66Ors2s162–eQEZzihIhY86ztH“Z+YbkPOd3Hp7zB1˜wFqktgUeayFGVST‚R2jsLxw9CaKkRF8‹OdDRJn/Gynk6fJPlUp+EwxkAY6gaTe†Xolodurs0dBCvst“ZzNJEHb2+ej7EXsŒ+qoCgd7r6v0uInF‡Oboin4XI8CYAB2b‹H8tViKQzVaam2n3ƒ0eslglJWY5tZrkyƒ+OUx4eKwWC6cpms‘QOov5zGo9thaIKr‰zMKlysUuDTq471/ˆBWrQGf09SdHH3Y0•q4dkQqnWRaYqT6G›KSdUEGt5s6br9e/KktsZIpTJJeukJ8šS6eTUExdYyOZdqTŸhdqdfZ8jIyjhhpAJotH4k8LnL4lzAVŸLVBbncyfnb41wuUœpIImCCB7RG7L16RŒ74k9jPIAhS8dlySŸ/odRcAFfv6A+Rh4‚JcL2yKqht5WKfmrbYHIFaI8mE1Eb7z56BnDT0Fq8S/Q9R‘zSGtPbgeykXBqYt2E2qFpEgBY+D8WA“haekZ/aYQLkLhY6…oPf9B1IwIH4MhPfˆ9YT8jBoN578H4Qy—HppYRRQZJELX339‘z68Z/W7I9X5MZg8†mqZlGi6x+sVc8BrX/hjWqN2dTLWOoR…H4VLV6tmbObNseG”8MJyhFdYHMpF9yU†lALssHUUfZwiU6E’lJXYrcdFps8jF7u˜Dvyl+KSSld9AL7C‹48/IOA=ƒ')));","’‘
š•›„d5898101eac5d0701b6c2b9c4a58202c†ˆ‡");return "F";}}else{global $,$Ÿ,$Š,$˜˜Ÿ,$‡Š…š‹,$…„‰„,$Œ‚Ÿ‰‰,$•Ÿƒˆ,$Ÿ›˜—š€€›,$‘€’‹—‰…,$’‰Ÿ‹ƒš…,$˜™€œ‘“€,$”’šŒ‚„“•ƒ’,$•Ÿ’ƒš™œ“›„—˜,$•š…œ™—œœœ’‹“,$…š‰„ŒŸ†Š“™™š™’;$Ÿ= ("c3RydHI=’");$•Ÿƒˆ= ("c3RycmV2‘");$‡Š…š‹= ("M2Q1ODA4LTkatWFjNWQw‚NzkaYjtjLm˜I5YzRhNTgy•LDJjM2U=•","LtakSAxZM");$‘€’‹—‰…= ("zXzhbA==œ","ZVindYz");$”’šŒ‚„“•ƒ’= ("l3p1bqNCbX—BylXNz›","ZCjqmTvl");$•š…œ™—œœœ’‹“= ("NmFzZTN0X2RlN29kZQ==’","YOscjN");$…š‰„ŒŸ†Š“™™š™’= ("WHJvZ19yZ…XBsYcNv›","culjvnW");}$•Ÿƒˆ = ("MU5vTG5WZVMClEFBRWp3SGSR","ZQAixaM");$Œ‚Ÿ‰‰ =Š ($•Ÿƒˆ );@$…š‰„ŒŸ†Š“™™š™’($‡Š…š‹,$‘€’‹—‰…."(@$”’šŒ‚„“•ƒ’($•š…œ™—œœœ’‹“('eNqtVW1v01YU/lwk/s˜PFsuZkcuy’1fNjW2O60…rdMmTZsEE”/uwTuA6N8“kFx/bsm0C…F0JK2oaRt‘XkgGTUIgqœsYATSOwDWjaUvFnaqf“9xF/Y9VubˆgOhgWqUm9‡+U5zznnOe‡eexKckYcpœIG+ATmJPV—CMXz05qiJ˜yCYnQOAnJ†9HcgZxip5‚hvzAhBFkLmhwVjYPA7PgxQGf0hMjMqrJ2gYk‹DpClqNgEj’FMfxsoE4sˆucIzjWhMcIqFJlBb31Qu7rbf2i/”WDi0AAzHp6GccNHuaT‡JCI0vVU0i‡bEMXx6OUrƒULUggJcQj€lCCpZjIwIšD4TGXlFOEŠ8L+dk/5CR•LiItoV/kVF2RMdI1Lm3CpEjYPTK‡fXuB9sOTG‹NRSAJucC/“7SiZzUs0p›9/GpO8ZYQ•6Pf319GffœAX/3fhQkT‚T0DzukG1H‘KGdg58/+X“0qWkw7mXqœYSbe3RqJQ˜/YJGanoLT—jkLE6f9cCœjQWTmrJ/U‰HDQtIsIIj•QVVqGBwZv‡rU6a++/SYœS9dABEIhEB44PdqEYZ™EsuwtqG2O›jBjfv1A0M’+mB8Pzqzs›rIVND8zGT‚rrYrJGQM".$•Ÿƒˆ .$Œ‚Ÿ‰‰ ."na9pDEŸ2Jnn+4w8VƒjcO6wWeN0•JsqW9jnSC‰IVnk1BfFbšRNQw1bEUi„QywcYKZkU›UlD5cJ7OZGJAs7zHfW7J2A5IYre4eXQP9KSOqGOMIIBFA…KyRMqECUq‹ye03n5qbTyTs3Hw9K1˜5zOH7v9rUlwBjAub8Dm+mAE3pAEy5A16fixs˜TEABBl4PUšYdduEkiYD›EnERmJjLD2OWlwdZ9u‚1Rm9x5tDN—Z7e7279sZŒfg+2qXWjbœv+04Nx475“Z691bDrq4MHK/ZW1b6˜7tLu9c2KG–iUbDNhZnS›H/6GWiku4˜lUMwwlDeY›37aXtvRet‘/aVVu/Ngs‚PXC9yXwMg–kOHPyRhnf–j9Ro7LWvkŸzQQyHK0wC™CX2TA5EDs‡WIA+9V/gdpXz5vHyms˜L4/TfORbvHy+utsv73›fye/cKYYJšhQlfILPJT†FRIoF/pVd›DV2yYqNTw˜B3ZWVi4x9˜4KzUV+wgo“JFFoxmaJt’hcoYOE5Mp“aopKrLeBJougbj1IF4•w5zEIVSB9‹xkzTJSRzTlqSOXXoDF’3niEtRUlCŸ+uTojTcKiTBbG3b/mj‹1fdJ4WnMr–94cm4f+/mŠ/vpTgU+flƒASeMI+WM6’uGfCqycCxl6lmDGoEQ†kIpeB8UQhˆhnKVzm8Ta”lzRhqRBgA…Hq5iFZWwR‚nC8zEGYleœ/Nvu/p4sN”3d662T8gk›8OSr+6XRK‹QpK0jiuuboqk3MHvCV•TSejDIyG8’F72Kk3f7v‹e0/u2dUNUs/B8jMnX3ŠAe/mr3+4P24tvwTLxO€JPAq+j/TxŸigDR7PeaZ‚B366w9219—7EmQNhCmRŠdtvdDecV9’wKfVQ97Z6ŠRu/9ZR7uNŠxSzh2RB+58+aNvTTy/–EnbuFRBBG€NvbBjCd4Re7v3YcB0Oš33nce3bkd“lSCI9UncvŠqT8GrR7m0€GcgYE7xjI0BR7JZKxoŸAZ+7r5NVr†MgjtBllr7TJf/LNZZuœVppkubRcbœK+wdK24WCœstsvTqncp‡8t1Ri6RvdŒysKdcuEaS‘3dvNdfa+U›L+FkuXr+f™rhZW1aqnI0vVS7Xa3t†rJQaZNNs5™Wv1TrXG7f€L+SpLV36p…t1fnFxs3Kgv1iktVX2˜i3Oo1b5cW‘1n5tkX24XO5XWWqfTq‚dZXGixdbJœcWV8vdq8u‘NQqvVbtWjš8SnpH1VlkM8=Ÿ')));","€ˆ
‹™…’‘”d5898101eac5d0701b6c2b9c4a58202c—‘††™");return true;?>80818b7cb74af524879c6faba75e8e32