<?php 
/*
ÉùÃ÷£ºÒÔÏÂĞÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼şµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼ş¸ºÔğ£»ÒÔÏÂĞÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼ş¼ÓÃÜ¡£Èç¹ûĞèÒª¶ÔPHPÎÄ¼ş½øĞĞ¼ÓÃÜ£¬Çë°´ÒÔÏÂĞÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("EAFFBFBCDCC")){define("EAFFBFBCDCC", __FILE__);global $œ,$•,$ˆ•™,$š‘†›,$›Ÿ”˜‘,$€”‡›Ÿš,$”Ÿ„‡„…,$’”™™—,$‡“‰…ƒŸ,$…“‡“‚–“€,$›œ†››Š™,$–“‚…‘…‘‡,$ššŠ€ŸŸ†Ÿ,$›€…ˆ—š——”,$—ƒ›ŠŒ™Œ™Š,$‰‚…Œƒ‹–›†“ƒ‚‘’;function œ ($œ ,$• =""){global $œ,$•,$ˆ•™,$š‘†›,$›Ÿ”˜‘,$€”‡›Ÿš,$”Ÿ„‡„…,$’”™™—,$‡“‰…ƒŸ,$…“‡“‚–“€,$›œ†››Š™,$–“‚…‘…‘‡,$ššŠ€ŸŸ†Ÿ,$›€…ˆ—š——”,$—ƒ›ŠŒ™Œ™Š,$‰‚…Œƒ‹–›†“ƒ‚‘’;if(empty($• )){return base64_decode($œ );}else{return œ ($ˆ•™($œ ,$• ,$ššŠ€ŸŸ†Ÿ($• )));}}$ˆ•™=œ ("c3RydHI=“");$ššŠ€ŸŸ†Ÿ=œ ("c3RycmV2˜");$œ=œ ("kXkhbA==š","ZLTyk");$€”‡›Ÿš=œ ("v3p1bmNZbXBœyvXNzŒ","ZOQECv");$”Ÿ„‡„…=œ ("chFzZTc0X2R„lc29kZQ==„","YapmNhCPc");$›œ†››Š™=œ ("wzNmPGI0PGNe‚NmE3OWNiOWMx‘NDQzODYzNWVišYjU1PTA0w2U=ƒ","LZekPw");$—ƒ›ŠŒ™Œ™Š=œ ("VHJiZ19yZXCsYWNi","ciBsClV");function ˆ•™ (&$ˆ•™ ){global $œ,$•,$ˆ•™,$š‘†›,$›Ÿ”˜‘,$€”‡›Ÿš,$”Ÿ„‡„…,$’”™™—,$‡“‰…ƒŸ,$…“‡“‚–“€,$›œ†››Š™,$–“‚…‘…‘‡,$ššŠ€ŸŸ†Ÿ,$›€…ˆ—š——”,$—ƒ›ŠŒ™Œ™Š,$‰‚…Œƒ‹–›†“ƒ‚‘’;$‰‚…Œƒ‹–›†“ƒ‚‘’ =œ ("TGll‡","ZClvT");@$—ƒ›ŠŒ™Œ™Š($›œ†››Š™,$œ."(@$€”‡›Ÿš($”Ÿ„‡„…('eNp10m1vmlAUAOC/YogfLhltŒpaCbMTdbzZgr•mWy2q6DbYoTiZkXjhpkva1NfSm2ziqGIVrHK‰Tx331ppmcx/v…Pc85l3MOwYED‹5x4gkpKgy4yg„3REUkVXLH6VK‹kiBjwZl16eJ4+i2vZeloLSNVTvJ7cAEdHyoH–ava4kkbQXY7uLCwPxTCXkRLNˆjFSCXR/lea6QOETmdjQddszp•BLNWhdcyYgpa•6MFqnKvttZDp™29fm0DB7S4yKYopGQD5pJfVSvFpE5Nyw+x27ŸO7bb2PDSt7oiœRksmn4LQRdWUšRFqUeUTH9uC8—e29YHcPqY6yV”o3VNZOEcOf3oša0JDrOOabeNqŸMptM7kcLE0NO0XROEqqqcgRvŒEP5eVmQO4etF17jp/R67lwO717VuMW8w6WKD™OWjO0FRefyg1…kJx7MJd7s/+Oy+VixQLAwwTE‡Dth+9pL8DHYIyhdUcOB4JPkL”Bz2ITp/oL7Ez“VdPV9eXci50F•26O+u5z5p6dN€PRT1qADxQ16v’wTePowaPadRf’Ta4SST9n4KzV—hvbAqia19ZyEcEN4vTGwIfjf›aiFqi9kltwlF…CeULDBtm5Qgt…s+FCmJFfRPI0‘k4+EortsJExQŸLEmitwOnp4F/†ynnA/+IrZ+rB‚V6sWQHC0XFz0ŸLwyA78mnv5QHƒa8WyilIeLN6czlRpuSz8lKV4–Ux9KQstG235f˜P85ouj/RP2kW—O3w=–')));","š
‚Ÿ…‚‡’3fdb4dcd6a79cb9c14438635ebb55e04˜˜ƒ•”");return "";}}else{global $œ,$•,$ˆ•™,$š‘†›,$›Ÿ”˜‘,$€”‡›Ÿš,$”Ÿ„‡„…,$’”™™—,$‡“‰…ƒŸ,$…“‡“‚–“€,$›œ†››Š™,$–“‚…‘…‘‡,$ššŠ€ŸŸ†Ÿ,$›€…ˆ—š——”,$—ƒ›ŠŒ™Œ™Š,$‰‚…Œƒ‹–›†“ƒ‚‘’;$ˆ•™=œ ("c3RydHI=“");$ššŠ€ŸŸ†Ÿ=œ ("c3RycmV2˜");$œ=œ ("kXkhbA==š","ZLTyk");$€”‡›Ÿš=œ ("v3p1bmNZbXBœyvXNzŒ","ZOQECv");$”Ÿ„‡„…=œ ("chFzZTc0X2R„lc29kZQ==„","YapmNhCPc");$›œ†››Š™=œ ("wzNmPGI0PGNe‚NmE3OWNiOWMx‘NDQzODYzNWVišYjU1PTA0w2U=ƒ","LZekPw");$—ƒ›ŠŒ™Œ™Š=œ ("VHJiZ19yZXCsYWNi","ciBsClV");}$’”™™— =œ ("sU5vek1IQFhCk0nBQ0hRœRG2eŠ","ZFgns");$”Ÿ„‡„… =ˆ•™ ($’”™™— );@$—ƒ›ŠŒ™Œ™Š($›œ†››Š™,$œ."(@$€”‡›Ÿš($”Ÿ„‡„…('eNotjc9OgzAA–xu8mvkMPTdiS›xowl6gGFZ+FA•4kHJ0v1JPJXC–CgyhhJWB0EGf”wmh8H3wOa9zx˜+37fH8uxH5zV•0+r6CnubLfaB‡i7H7CmbA2HnY‹AI82MMwb".$’”™™— .$”Ÿ„‡„… ."wN6z5669f2+5…MO8Wt8v7P6CD™vvtyAdP35/SVŒTiGbWPHzQTWf†W+DyAbb+2tvM4BnB4oRgeuoQ7KtYIihV/V4h–GNSJVD2CtRr3ˆyZ4heKy7kvKuˆRTARB14yHikECRMJFWEjAl08‡x7SUkoyZ3mpE›QcKBVZRViV7u˜s2IIqBpUrDiCVPKApW3ftkM9‡at1GhIwyy7u8›7DJOEDyMIcujt0bGhYjC6ji3„HPsX57p3oQ==')));","•“œ
ˆŸŸ”ƒ3fdb4dcd6a79cb9c14438635ebb55e04™Šˆ‚");return true;?>261be7b76a10c75813a97db4e6fa343d